### ISSUE TITLE
Web即时聊天用户在线状态监听

### ISSUE THREAD

**Issue by wzlzking** [IcedSoul/Gitment#16]
假如在移动端打开web即时聊天的话，想实现用户不在线时即通过微信模板或短信发送消息提醒，没发一条新消息，就发一条消息提醒（前提好友不在线），这时我想通过一些页面事件，pagehide、pageshow等监听用户是否还在此页面，但在ios上，特别是ios的微信浏览器（微信客户端打开）时，许多事件监听不到，请问您遇见过此类问题吗或者有什么解决方法吗？求指教！

**Comment by IcedSoul** [comment]
emm，怎么跑到这里开个新issue = =，直接在博客下面gitment评论或者withme项目开新issue才是常规操作吧 = =
我做项目没有考虑到web端手机浏览器的兼容性，因为电脑版UI和手机版UI要做两套，既然需要做两套UI不如直接做个app得了，花费的时间是一样的。  
微信浏览器的问题我没关注过。。。建议做app，实在想做成网页也可以把网页封装成app，据我所知android的webview可以很方便的把网页封装成app。ios我不太了解，应该也有类似的技术。建议不要纠结微信内置浏览器的问题。。。实在不行也可以做个小程序前台来解决在微信中的表现。。。。

**Comment by wzlzking** [comment]
不好意思啊，因为现在这个需求就是要做成web端手机里打开的，用的是腾讯云通信的sdk，所以没办法做成app，同样感谢您！

**Comment by IcedSoul** [comment]
你的意思是现在需求就是做一个手机Web的即时聊天工具，现在想要添加发送对象不在线时发送邮件或者短信或者微信公众号消息之类的操作对吧，如果是这样那么我说一下我的想法：  
首先你说的通过浏览器事件看用户是否仍然在当前页面，这是一个办法，但是这个方法似乎不太好：因为手机浏览器也可以后台运行的，用户只是离开页面不代表就下线了，可能连接还在保持着。  
如果我使用WebSocket解决这个问题的时候会考虑从下面解决，当A发送消息给B时，后台服务器会做校验，看B是否在线，如果在线直接转发，如果不在线调用其它通知方式的API。  
你提到你使用的是腾讯云通信的sdk，我刚刚查了一下，文档里面提到了它的C2C消息有接口校验接收方是否接收成功、是否在线的，你只需要在后台根据sdk提供接口的结果来调用邮件或者短信或者微信公众号之类的发送接口即可。  
希望对你解决这个问题有所帮助～

**Comment by wzlzking** [comment]
首先再次感谢您的回复，可能是我问题描述的不够准确，现在的需求就是只有用户不在我这个聊天室页面，他在我项目的别的页面、手机息屏或处于后台运行，他都算没有看到最新的消息的，所以都应该给他发消息提醒，还有您说的，腾讯sdk有判断是否接受成功和是否在线的接口，我没有选择这个接口的原因，1.获取好友的未读消息数，需要好友处于登录状态，才可以，2.而腾讯这个登录状态好像是有5分钟的误差的，就是用户在下线5分钟内，腾讯是不知道的。

**Comment by wzlzking** [comment]
而项目这个项目的需求是要尽量做到实时的，我现在采取的是ajax轮询，每10s一个心跳包，但依然感觉有10s的误差，也想过用websocket，但腾讯sdk里已经有一个websocket了，因为对websocket不太了解，不知道同一个页面可不可以有多个websocket

**Comment by IcedSoul** [comment]
一个页面可以有多个WebSocket连接。  
但是我觉得为了这个需求专门再写一个WebSocket服务器似乎代价有点大，你可以确认两个问题：
1. 咨询腾讯云通信客服确认登录状态5分钟延时是否正常，是否可避免。
2. ios浏览器事件我搜了一下貌似也有解决方法，因为不清楚你的具体情况所部不敢断言，你可以再了解下。


此外，根据你目前的描述，我还有个不成熟的想法：  
现在的需求是让用户看到最新消息，那么用户有两种情况，一种是未登录，一种是登录了但是没有及时查看，那么可以在两个地方发送通知。
1. 当给用户发送消息时，确认对方是否在线，发现不在线直接发送通知。发送失败也发送通知。（就算用户在线状态有延时，发送消息的状态应该能实时获取吧，sdk也会有处理的，要么发送失败，要么进入2情况。）
2. 消息成功发给了用户，但是用户没有看，那么可以给消息加上一个是否阅读的标签，在进行数据渲染时将消息改为已阅，如果收到的消息处理后没有变成已阅，那么仍然给用户发送通知。

因为对详细场景不是很清楚，只是说一下我的想法，如果不合实际还请见谅。

**Comment by wzlzking** [comment]
`我先说一下我在ios的问题啊，1.ios微信浏览器，点击微信浏览器左上角的叉号，监听不到，（我看了一下京东公众号可以监听的，但不知道是怎么做的，估计是定制的），2.在当前页面但是息屏时监听不到，3.在当前页面但进入多任务时监听不到，
var hidden,state, visibilityChange;
        if (typeof document.hidden !== "undefined") {
            hidden = "hidden";
            state = "visibilityState";
            visibilityChange = "visibilitychange";
        } else if (typeof document.mozHidden !== "undefined") {
            hidden = "mozHidden";
            state = "mozvisibilityState";
            visibilityChange = "mozvisibilitychange";
        } else if (typeof document.msHidden !== "undefined") {
            hidden = "msHidden";
            state = "msvisibilityState";
            visibilityChange = "msvisibilitychange";
        } else if (typeof document.webkitHidden !== "undefined") {
            hidden = "webkitHidden";
            state = "webkitvisibilityState";
            visibilityChange = "webkitvisibilitychange";
        }

         添加监听器，在title里显示状态变化
        document.addEventListener(visibilityChange, function () {
            console.log(document[state]);
            if (document[hidden]) {
                console.log('notInPage-'+document[state]+'-'+state);
                // 用户没有浏览当前页面
            } else {
                console.log('comeBack-'+document[state]+'-'+state);
                // 用户正在浏览当前页面
            }
        }, false);
通过这段js，我说的这些问题，安卓上都可以监听到，不管是自带浏览器还是微信浏览器
不知道您说的ios浏览器事件解决方法是什么，是否是我遇到的这些问题，方便发一个参考地址吗？`
还有您说的第二个情况也是我打算之后可以去切入的点。
再次感谢！

**Comment by IcedSoul** [comment]
我之前也没做过这种监听，就简单搜了一下资料：
1. IOS微信左上角关闭事件监听相关内容：
    1. https://www.zhihu.com/question/40511430
    2. https://www.jianshu.com/p/06b1f9738506?utm_campaign=maleskine&utm_content=note&utm_medium=seo_notes&utm_source=recommendation
    3. https://developers.weixin.qq.com/community/develop/doc/000a4e028300f8b07bd7ef9365d000
    我看第一个链接回答下面有人评论说IOS解决了，我简单对比了一下代码，可能与第二个链接中提到popstate事件有关，但是好像也只能监听返回事件，关闭事件是不行的。第三个链接中官方人员回复说京东可以但是微信没有提供，这个应该是无解的了。（毕竟外部关闭浏览器，微信不提供接口那就无解）很奇怪你Android是怎么监听到左上角关闭事件的。此外，有人提到了onbeforeunload，我不确定它能不能来得及执行，你可以试试。
2. 我找第二个问题时并没有找到答案，但是发现了一个有意思的内容：
    1. https://blog.csdn.net/hcl1687/article/details/47343553
    也就是说，在IOS锁屏是，一些js函数比如setTimeout会停止的，可以尝试下从这个角度来识别屏幕熄灭功能。

**Comment by IcedSoul** [comment]
第三个问题，如果你说的多任务是手机的多任务的话，如果手机系统没有自行处理，网页想要获取这种状态也是比较麻烦的，可以参考第二点看看有办法解决没。  
我也就是临时查了一下，很可能这些你都查到过了，个人这方面研究也不深，希望能有所帮助，没帮助也见谅，尽力了2333～

**Comment by wzlzking** [comment]
很高兴您一直抽空回答我的问题，十分感谢，上面除了最后一个链接我没看过，别的我也看过了，给的方法都是只能监听到返回，不能监听到退出，关于为什么在安卓上可以监听到，ios监听不到，可能是由于两个系统在处理后台运行时的方式不同吧，安卓应该是程序处于后台时，这个程序也是相当于在后台保持活跃的，ios应该是不在当前程序时，就暂时封存了吧，我也是理解的比较浅显。。。

**Comment by IcedSoul** [comment]
哈哈哈，可以开个计时器，停了就认为熄屏了哈哈哈，就怕写这样代码会领导打。。。我也没啥辙了，加油～

**Comment by wzlzking** [comment]
哈哈，好的，多谢，五一假期快乐！！！
