### ISSUE TITLE
Shopping+在线购物商城的实现（Spring+SpringMVC+Hibernate） | 冰魄的个人博客

### ISSUE THREAD

**Issue by IcedSoul** [IcedSoul/Gitment#4]
https://blog.icedsoul.cn/2019/01/15/shopping/#more 

 前言&nbsp;&nbsp;&nbsp;&nbsp;虽说之前我想要把自己做过的项目一一写成博客放出来，可是之前因为CSDN手机号验证什么的真的让我对它的不满爆发了，所以这么久以来没有写新的博客，因为我自己搭的博客还在建设中。但是既然之前说过要放项目，那么也不能食言，就把我做过的几个项目简单放上来吧，不做太多的解释。不废话了。 项目功能介绍&nbsp;&nbsp;&nbsp;&nbsp;本项目是一个

**Comment by DWuTao** [comment]
你好，那个图片无法上传到img文件夹，能说一下大概是哪里出了问题吗？

**Comment by DWuTao** [comment]
> 你好，那个图片无法上传到IMG文件夹，能说一下大概是哪里出了问题吗？

我现在重新打开都是看不到图片的

**Comment by IcedSoul** [comment]
> @DWuTao
> > 你好，那个图片无法上传到IMG文件夹，能说一下大概是哪里出了问题吗？
> 
> 我现在重新打开都是看不到图片的


> @DWuTao
> > 你好，那个图片无法上传到IMG文件夹，能说一下大概是哪里出了问题吗？
> 
> 我现在重新打开都是看不到图片的

图片上传功能我测试过没有问题，如果你本地运行没有上传成功。首先检查图片大小是否合适，其次依次确认以下几点：  
1. 是否提示上传失败或者前端上传报错，确认问题出现在前端还是后端。如果前端控制台报错你无法解决，请截图mail或者qq群发出来询问。如果确认前端没有问题，看下一点。
2.  查看控制台是否报错，报什么错，在错误点打断点调试看具体是哪一行代码，如果不理解为什么出错或者不知道怎么修改，可以吧错误截图和错误代码行截图给我。
3. 如果后端也没有任何报错，前端也提示上传成功，那么刷新一下页面后，图片应该能够显示了。如果图片仍然不能正常显示，那么检查对应文件夹是否有相关图片：注意检查文件夹的路径为 你部署项目的Tomcat根目录+ /webapps 下对应文件夹，而不是你部署之前的项目的文件夹。如果没有发现文件，可以加QQ群详细反馈我来检查。  
群：790614596 加群备注：icedsoul blog

**Comment by DWuTao** [comment]
> @IcedSoul
> > @DWuTao
> > > 你好，那个图片无法上传到IMG文件夹，能说一下大概是哪里出了问题吗？
> > 
> > 我现在重新打开都是看不到图片的
> 
> 
> > @DWuTao
> > > 你好，那个图片无法上传到IMG文件夹，能说一下大概是哪里出了问题吗？
> > 
> > 我现在重新打开都是看不到图片的
> 
> 图片上传功能我测试过没有问题，如果你本地运行没有上传成功。首先检查图片大小是否合适，其次依次确认以下几点：  
> 1. 是否提示上传失败或者前端上传报错，确认问题出现在前端还是后端。如果前端控制台报错你无法解决，请截图mail或者qq群发出来询问。如果确认前端没有问题，看下一点。
> 2.  查看控制台是否报错，报什么错，在错误点打断点调试看具体是哪一行代码，如果不理解为什么出错或者不知道怎么修改，可以吧错误截图和错误代码行截图给我。
> 3. 如果后端也没有任何报错，前端也提示上传成功，那么刷新一下页面后，图片应该能够显示了。如果图片仍然不能正常显示，那么检查对应文件夹是否有相关图片：注意检查文件夹的路径为 你部署项目的Tomcat根目录+ /webapps 下对应文件夹，而不是你部署之前的项目的文件夹。如果没有发现文件，可以加QQ群详细反馈我来检查。  
> 群：790614596 加群备注：icedsoul blog

感谢博主的及时回复！
这个问题是我没有仔细看代码，以为是文件是上传到我项目的文件夹里，看了代码后才发现是上传到TOMCAT服务器根目录的IMG文件夹上，然后我每次重启服务器，文件夹都会初始化，所以我每次重新打开才会看不到图片。
再次感谢博主的解答！
